'use client'

import { useState } from 'react'
import { FileText, Download, Settings } from 'lucide-react'

interface ReportOptions {
  includeCharts: boolean
  includeTimestamps: boolean
  includeEmissions: boolean
  format: 'pdf' | 'csv' | 'json'
}

interface ReportGeneratorProps {
  baselineMetrics?: any
  btutMetrics?: any
  onGenerate?: (options: ReportOptions) => void
}

export default function ReportGenerator({ baselineMetrics, btutMetrics, onGenerate }: ReportGeneratorProps) {
  const [options, setOptions] = useState<ReportOptions>({
    includeCharts: true,
    includeTimestamps: true,
    includeEmissions: true,
    format: 'pdf'
  })

  const [showOptions, setShowOptions] = useState(false)

  const handleGenerate = () => {
    if (onGenerate) {
      onGenerate(options)
    } else {
      // Default behavior: generate mock report
      generateMockReport()
    }
  }

  const generateMockReport = () => {
    const reportContent = `
BTUT TRAFFIC SIMULATION REPORT
=============================
Generated: ${new Date().toLocaleString()}

EXECUTIVE SUMMARY
-----------------
${baselineMetrics && btutMetrics ? `
Baseline vs BTUT Comparison:
- Average Speed: ${baselineMetrics.averageSpeed.toFixed(1)} km/h → ${btutMetrics.averageSpeed.toFixed(1)} km/h
- Throughput: ${baselineMetrics.throughput} → ${btutMetrics.throughput} vehicles/hour
- Waiting Time: ${baselineMetrics.waitingTime.toFixed(1)}s → ${btutMetrics.waitingTime.toFixed(1)}s

IMPROVEMENTS:
- Speed: ${(((btutMetrics.averageSpeed - baselineMetrics.averageSpeed) / baselineMetrics.averageSpeed) * 100).toFixed(1)}%
- Throughput: ${(((btutMetrics.throughput - baselineMetrics.throughput) / baselineMetrics.throughput) * 100).toFixed(1)}%
- Queue Reduction: ${(((baselineMetrics.waitingTime - btutMetrics.waitingTime) / baselineMetrics.waitingTime) * 100).toFixed(1)}%
` : 'No metrics available'}

METHODOLOGY
-----------
BTUT (Bivariate Trajectory-Undercurrent Theory) uses mean-field game theory
to coordinate vehicles in real-time, optimizing for collective throughput
while minimizing individual delays.

PARAMETERS:
- Gamma (γ): 1.5 (cooperation bonus)
- Tau (τ): 0.3 (hub influence)

CONCLUSION
----------
BTUT coordination demonstrates significant improvements in traffic flow
metrics compared to uncoordinated baseline traffic.

---
Generated by BTUT Platform v1.0
`

    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `btut-traffic-report-${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="bg-gray-900/50 backdrop-blur border border-gray-800 rounded-xl p-6">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <FileText className="w-5 h-5 text-neon-purple" />
          Report Generator
        </h3>
        <button
          onClick={() => setShowOptions(!showOptions)}
          className="p-2 hover:bg-gray-800 rounded-lg transition"
        >
          <Settings className="w-4 h-4 text-gray-400" />
        </button>
      </div>

      {/* Options */}
      {showOptions && (
        <div className="mb-6 space-y-4">
          <div>
            <label className="text-sm text-gray-400 mb-2 block">Report Format</label>
            <div className="grid grid-cols-3 gap-2">
              <button
                onClick={() => setOptions(prev => ({ ...prev, format: 'pdf' }))}
                className={`px-4 py-2 rounded-lg text-sm font-semibold transition ${
                  options.format === 'pdf'
                    ? 'bg-neon-purple text-black'
                    : 'bg-gray-800 text-gray-400 hover:bg-gray-700'
                }`}
              >
                PDF
              </button>
              <button
                onClick={() => setOptions(prev => ({ ...prev, format: 'csv' }))}
                className={`px-4 py-2 rounded-lg text-sm font-semibold transition ${
                  options.format === 'csv'
                    ? 'bg-neon-purple text-black'
                    : 'bg-gray-800 text-gray-400 hover:bg-gray-700'
                }`}
              >
                CSV
              </button>
              <button
                onClick={() => setOptions(prev => ({ ...prev, format: 'json' }))}
                className={`px-4 py-2 rounded-lg text-sm font-semibold transition ${
                  options.format === 'json'
                    ? 'bg-neon-purple text-black'
                    : 'bg-gray-800 text-gray-400 hover:bg-gray-700'
                }`}
              >
                JSON
              </button>
            </div>
          </div>

          <div className="space-y-2">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={options.includeCharts}
                onChange={(e) => setOptions(prev => ({ ...prev, includeCharts: e.target.checked }))}
                className="w-4 h-4 rounded border-gray-700 bg-gray-800 text-neon-purple focus:ring-neon-purple"
              />
              <span className="text-sm text-gray-400">Include charts and visualizations</span>
            </label>

            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={options.includeTimestamps}
                onChange={(e) => setOptions(prev => ({ ...prev, includeTimestamps: e.target.checked }))}
                className="w-4 h-4 rounded border-gray-700 bg-gray-800 text-neon-purple focus:ring-neon-purple"
              />
              <span className="text-sm text-gray-400">Include timestamps</span>
            </label>

            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={options.includeEmissions}
                onChange={(e) => setOptions(prev => ({ ...prev, includeEmissions: e.target.checked }))}
                className="w-4 h-4 rounded border-gray-700 bg-gray-800 text-neon-purple focus:ring-neon-purple"
              />
              <span className="text-sm text-gray-400">Include emissions data</span>
            </label>
          </div>
        </div>
      )}

      {/* Report Preview */}
      <div className="mb-6 bg-gray-800/50 border border-gray-700 rounded-xl p-4">
        <div className="text-xs text-gray-400 mb-2">Report Preview:</div>
        <div className="space-y-1 text-sm text-gray-500 font-mono">
          <div>📊 Executive Summary</div>
          <div>📈 Performance Metrics</div>
          <div>🔄 Before/After Comparison</div>
          {options.includeCharts && <div>📉 Charts & Graphs</div>}
          {options.includeEmissions && <div>🌍 Environmental Impact</div>}
          <div>📋 Methodology</div>
          <div>💡 Recommendations</div>
        </div>
      </div>

      {/* Generate Button */}
      <button
        onClick={handleGenerate}
        disabled={!baselineMetrics && !btutMetrics}
        className="w-full px-6 py-3 bg-gradient-to-r from-neon-purple to-neon-pink hover:shadow-lg hover:shadow-neon-purple/50 disabled:from-gray-700 disabled:to-gray-700 disabled:text-gray-500 text-black font-bold rounded-lg transition flex items-center justify-center gap-2"
      >
        <Download className="w-5 h-5" />
        Generate {options.format.toUpperCase()} Report
      </button>

      {/* Info */}
      <div className="mt-4 text-xs text-gray-500 text-center">
        Reports include detailed analysis, charts, and actionable insights
      </div>
    </div>
  )
}
